"""OAuth provider protocol — uniform interface for all providers.

Each provider (GitHub, Google, Notion) implements this protocol.
OAuthManager uses this interface without knowing provider-specific details.

The protocol enforces browser-based OAuth (no Device Flow).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from nally.oauth.models import OAuthResult, OAuthSession, OAuthToken


@runtime_checkable
class OAuthProvider(Protocol):
    """Uniform interface for OAuth providers.

    This protocol defines the contract that all providers must implement.
    Providers own the OAuth-specific mechanics (endpoints, scopes, PKCE).
    NALLY owns the lifecycle (begin → callback → store).

    Usage:
        provider = GitHubProvider()
        session = await provider.begin(user_id, redirect_uri)
        # Send session.authorization_url to Telegram
        # Wait for callback
        result = await provider.callback(state, code)
        # Store result.token in TokenStore
    """

    @property
    def provider_name(self) -> str:
        """Return the provider identifier (github, google, notion)."""
        ...

    @property
    def requires_pkce(self) -> bool:
        """Whether this provider requires PKCE."""
        ...

    @property
    def scopes(self) -> list[str]:
        """Return the scopes this provider requests."""
        ...

    async def begin(
        self,
        user_id: str,
        redirect_uri: str,
        state: str,
        code_challenge: str | None = None,
    ) -> OAuthSession:
        """Start an OAuth flow.

        Args:
            user_id: The user initiating the flow
            redirect_uri: Where to redirect after authorization
            state: OAuth state (generated by OAuthFlowStore, must be used in auth URL)
            code_challenge: PKCE code challenge (if required)

        Returns:
            OAuthSession with authorization_url for the user to visit
        """
        ...

    async def callback(
        self,
        code: str,
        state: str,
        code_verifier: str | None = None,
        redirect_uri: str | None = None,
    ) -> OAuthResult:
        """Handle OAuth callback.

        Args:
            code: Authorization code from provider
            state: OAuth state parameter for validation
            code_verifier: PKCE code verifier (if used)
            redirect_uri: Redirect URI used in begin() (must match for exchange)

        Returns:
            OAuthResult with token and user info

        Raises:
            OAuthError: If code exchange fails
        """
        ...

    async def refresh(self, token: OAuthToken) -> OAuthToken:
        """Refresh an expired token.

        Args:
            token: The expired token to refresh

        Returns:
            New OAuthToken with fresh access_token

        Raises:
            OAuthError: If refresh fails (user must re-authenticate)
        """
        ...

    async def revoke(self, token: OAuthToken) -> bool:
        """Revoke a token with the provider.

        Args:
            token: The token to revoke

        Returns:
            True if revocation succeeded
        """
        ...

    def format_auth_headers(self, token: OAuthToken) -> dict[str, str]:
        """Format token as HTTP headers for MCP transport.

        Args:
            token: The token to format

        Returns:
            Dict of headers (e.g., {"Authorization": "Bearer ..."})
        """
        ...

    def format_auth_env(self, token: OAuthToken) -> dict[str, str]:
        """Format token as environment variables for MCP stdio transport.

        Args:
            token: The token to format

        Returns:
            Dict of env vars (e.g., {"GITHUB_TOKEN": "..."})
        """
        ...
